<?php

namespace App\Support;

class CurrencyList
{
    /**
     * All Stripe-supported currencies with their display names and symbols.
     * Source: https://stripe.com/docs/currencies
     */
    public static function all(): array
    {
        return [
            'AED' => ['name' => 'UAE Dirham',               'symbol' => 'د.إ'],
            'AFN' => ['name' => 'Afghan Afghani',            'symbol' => '؋'],
            'ALL' => ['name' => 'Albanian Lek',              'symbol' => 'L'],
            'AMD' => ['name' => 'Armenian Dram',             'symbol' => '֏'],
            'ANG' => ['name' => 'Netherlands Antillean Guilder', 'symbol' => 'ƒ'],
            'AOA' => ['name' => 'Angolan Kwanza',            'symbol' => 'Kz'],
            'ARS' => ['name' => 'Argentine Peso',            'symbol' => '$'],
            'AUD' => ['name' => 'Australian Dollar',         'symbol' => 'A$'],
            'AWG' => ['name' => 'Aruban Florin',             'symbol' => 'ƒ'],
            'AZN' => ['name' => 'Azerbaijani Manat',         'symbol' => '₼'],
            'BAM' => ['name' => 'Bosnia-Herzegovina Mark',   'symbol' => 'KM'],
            'BBD' => ['name' => 'Barbadian Dollar',          'symbol' => 'Bds$'],
            'BDT' => ['name' => 'Bangladeshi Taka',          'symbol' => '৳'],
            'BGN' => ['name' => 'Bulgarian Lev',             'symbol' => 'лв'],
            'BIF' => ['name' => 'Burundian Franc',           'symbol' => 'Fr'],
            'BMD' => ['name' => 'Bermudian Dollar',          'symbol' => '$'],
            'BND' => ['name' => 'Brunei Dollar',             'symbol' => 'B$'],
            'BOB' => ['name' => 'Bolivian Boliviano',        'symbol' => 'Bs.'],
            'BRL' => ['name' => 'Brazilian Real',            'symbol' => 'R$'],
            'BSD' => ['name' => 'Bahamian Dollar',           'symbol' => 'B$'],
            'BWP' => ['name' => 'Botswanan Pula',            'symbol' => 'P'],
            'BYN' => ['name' => 'Belarusian Ruble',          'symbol' => 'Br'],
            'BZD' => ['name' => 'Belize Dollar',             'symbol' => 'BZ$'],
            'CAD' => ['name' => 'Canadian Dollar',           'symbol' => 'CA$'],
            'CDF' => ['name' => 'Congolese Franc',           'symbol' => 'Fr'],
            'CHF' => ['name' => 'Swiss Franc',               'symbol' => 'CHF'],
            'CLP' => ['name' => 'Chilean Peso',              'symbol' => '$'],
            'CNY' => ['name' => 'Chinese Yuan',              'symbol' => '¥'],
            'COP' => ['name' => 'Colombian Peso',            'symbol' => '$'],
            'CRC' => ['name' => 'Costa Rican Colón',         'symbol' => '₡'],
            'CVE' => ['name' => 'Cape Verdean Escudo',       'symbol' => '$'],
            'CZK' => ['name' => 'Czech Koruna',              'symbol' => 'Kč'],
            'DJF' => ['name' => 'Djiboutian Franc',          'symbol' => 'Fr'],
            'DKK' => ['name' => 'Danish Krone',              'symbol' => 'kr'],
            'DOP' => ['name' => 'Dominican Peso',            'symbol' => 'RD$'],
            'DZD' => ['name' => 'Algerian Dinar',            'symbol' => 'د.ج'],
            'EGP' => ['name' => 'Egyptian Pound',            'symbol' => 'E£'],
            'ETB' => ['name' => 'Ethiopian Birr',            'symbol' => 'Br'],
            'EUR' => ['name' => 'Euro',                      'symbol' => '€'],
            'FJD' => ['name' => 'Fijian Dollar',             'symbol' => 'FJ$'],
            'FKP' => ['name' => 'Falkland Islands Pound',    'symbol' => '£'],
            'GBP' => ['name' => 'British Pound',             'symbol' => '£'],
            'GEL' => ['name' => 'Georgian Lari',             'symbol' => '₾'],
            'GIP' => ['name' => 'Gibraltar Pound',           'symbol' => '£'],
            'GMD' => ['name' => 'Gambian Dalasi',            'symbol' => 'D'],
            'GNF' => ['name' => 'Guinean Franc',             'symbol' => 'Fr'],
            'GTQ' => ['name' => 'Guatemalan Quetzal',        'symbol' => 'Q'],
            'GYD' => ['name' => 'Guyanese Dollar',           'symbol' => 'G$'],
            'HKD' => ['name' => 'Hong Kong Dollar',          'symbol' => 'HK$'],
            'HNL' => ['name' => 'Honduran Lempira',          'symbol' => 'L'],
            'HTG' => ['name' => 'Haitian Gourde',            'symbol' => 'G'],
            'HUF' => ['name' => 'Hungarian Forint',          'symbol' => 'Ft'],
            'IDR' => ['name' => 'Indonesian Rupiah',         'symbol' => 'Rp'],
            'ILS' => ['name' => 'Israeli New Shekel',        'symbol' => '₪'],
            'INR' => ['name' => 'Indian Rupee',              'symbol' => '₹'],
            'ISK' => ['name' => 'Icelandic Króna',           'symbol' => 'kr'],
            'JMD' => ['name' => 'Jamaican Dollar',           'symbol' => 'J$'],
            'JPY' => ['name' => 'Japanese Yen',              'symbol' => '¥'],
            'KES' => ['name' => 'Kenyan Shilling',           'symbol' => 'KSh'],
            'KGS' => ['name' => 'Kyrgyzstani Som',           'symbol' => 'лв'],
            'KHR' => ['name' => 'Cambodian Riel',            'symbol' => '៛'],
            'KMF' => ['name' => 'Comorian Franc',            'symbol' => 'Fr'],
            'KRW' => ['name' => 'South Korean Won',          'symbol' => '₩'],
            'KYD' => ['name' => 'Cayman Islands Dollar',     'symbol' => 'CI$'],
            'KZT' => ['name' => 'Kazakhstani Tenge',         'symbol' => '₸'],
            'LAK' => ['name' => 'Laotian Kip',               'symbol' => '₭'],
            'LBP' => ['name' => 'Lebanese Pound',            'symbol' => 'L£'],
            'LKR' => ['name' => 'Sri Lankan Rupee',          'symbol' => 'Rs'],
            'LRD' => ['name' => 'Liberian Dollar',           'symbol' => 'L$'],
            'LSL' => ['name' => 'Lesotho Loti',              'symbol' => 'L'],
            'MAD' => ['name' => 'Moroccan Dirham',           'symbol' => 'د.م.'],
            'MDL' => ['name' => 'Moldovan Leu',              'symbol' => 'L'],
            'MGA' => ['name' => 'Malagasy Ariary',           'symbol' => 'Ar'],
            'MKD' => ['name' => 'Macedonian Denar',          'symbol' => 'ден'],
            'MMK' => ['name' => 'Myanmar Kyat',              'symbol' => 'K'],
            'MNT' => ['name' => 'Mongolian Tögrög',          'symbol' => '₮'],
            'MOP' => ['name' => 'Macanese Pataca',           'symbol' => 'P'],
            'MUR' => ['name' => 'Mauritian Rupee',           'symbol' => 'Rs'],
            'MVR' => ['name' => 'Maldivian Rufiyaa',         'symbol' => 'Rf'],
            'MWK' => ['name' => 'Malawian Kwacha',           'symbol' => 'MK'],
            'MXN' => ['name' => 'Mexican Peso',              'symbol' => '$'],
            'MYR' => ['name' => 'Malaysian Ringgit',         'symbol' => 'RM'],
            'MZN' => ['name' => 'Mozambican Metical',        'symbol' => 'MT'],
            'NAD' => ['name' => 'Namibian Dollar',           'symbol' => 'N$'],
            'NGN' => ['name' => 'Nigerian Naira',            'symbol' => '₦'],
            'NIO' => ['name' => 'Nicaraguan Córdoba',        'symbol' => 'C$'],
            'NOK' => ['name' => 'Norwegian Krone',           'symbol' => 'kr'],
            'NPR' => ['name' => 'Nepalese Rupee',            'symbol' => 'Rs'],
            'NZD' => ['name' => 'New Zealand Dollar',        'symbol' => 'NZ$'],
            'PAB' => ['name' => 'Panamanian Balboa',         'symbol' => 'B/.'],
            'PEN' => ['name' => 'Peruvian Sol',              'symbol' => 'S/'],
            'PGK' => ['name' => 'Papua New Guinean Kina',    'symbol' => 'K'],
            'PHP' => ['name' => 'Philippine Peso',           'symbol' => '₱'],
            'PKR' => ['name' => 'Pakistani Rupee',           'symbol' => 'Rs'],
            'PLN' => ['name' => 'Polish Zloty',              'symbol' => 'zł'],
            'PYG' => ['name' => 'Paraguayan Guaraní',        'symbol' => '₲'],
            'QAR' => ['name' => 'Qatari Riyal',              'symbol' => 'ر.ق'],
            'RON' => ['name' => 'Romanian Leu',              'symbol' => 'lei'],
            'RSD' => ['name' => 'Serbian Dinar',             'symbol' => 'дин'],
            'RUB' => ['name' => 'Russian Ruble',             'symbol' => '₽'],
            'RWF' => ['name' => 'Rwandan Franc',             'symbol' => 'Fr'],
            'SAR' => ['name' => 'Saudi Riyal',               'symbol' => 'ر.س'],
            'SBD' => ['name' => 'Solomon Islands Dollar',    'symbol' => 'SI$'],
            'SCR' => ['name' => 'Seychellois Rupee',         'symbol' => 'Rs'],
            'SEK' => ['name' => 'Swedish Krona',             'symbol' => 'kr'],
            'SGD' => ['name' => 'Singapore Dollar',          'symbol' => 'S$'],
            'SHP' => ['name' => 'Saint Helena Pound',        'symbol' => '£'],
            'SLE' => ['name' => 'Sierra Leonean Leone',      'symbol' => 'Le'],
            'SOS' => ['name' => 'Somali Shilling',           'symbol' => 'Sh'],
            'SRD' => ['name' => 'Surinamese Dollar',         'symbol' => '$'],
            'STD' => ['name' => 'São Tomé & Príncipe Dobra', 'symbol' => 'Db'],
            'SZL' => ['name' => 'Swazi Lilangeni',           'symbol' => 'L'],
            'THB' => ['name' => 'Thai Baht',                 'symbol' => '฿'],
            'TJS' => ['name' => 'Tajikistani Somoni',        'symbol' => 'SM'],
            'TOP' => ['name' => 'Tongan Paʻanga',            'symbol' => 'T$'],
            'TRY' => ['name' => 'Turkish Lira',              'symbol' => '₺'],
            'TTD' => ['name' => 'Trinidad & Tobago Dollar',  'symbol' => 'TT$'],
            'TWD' => ['name' => 'New Taiwan Dollar',         'symbol' => 'NT$'],
            'TZS' => ['name' => 'Tanzanian Shilling',        'symbol' => 'Sh'],
            'UAH' => ['name' => 'Ukrainian Hryvnia',         'symbol' => '₴'],
            'UGX' => ['name' => 'Ugandan Shilling',          'symbol' => 'Sh'],
            'USD' => ['name' => 'US Dollar',                 'symbol' => '$'],
            'UYU' => ['name' => 'Uruguayan Peso',            'symbol' => '$U'],
            'UZS' => ['name' => 'Uzbekistani Som',           'symbol' => 'лв'],
            'VES' => ['name' => 'Venezuelan Bolívar',        'symbol' => 'Bs.S'],
            'VND' => ['name' => 'Vietnamese Dong',           'symbol' => '₫'],
            'VUV' => ['name' => 'Vanuatu Vatu',              'symbol' => 'Vt'],
            'WST' => ['name' => 'Samoan Tala',               'symbol' => 'T'],
            'XAF' => ['name' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'XCD' => ['name' => 'East Caribbean Dollar',     'symbol' => 'EC$'],
            'XOF' => ['name' => 'West African CFA Franc',    'symbol' => 'Fr'],
            'XPF' => ['name' => 'CFP Franc',                 'symbol' => 'Fr'],
            'YER' => ['name' => 'Yemeni Rial',               'symbol' => '﷼'],
            'ZAR' => ['name' => 'South African Rand',        'symbol' => 'R'],
            'ZMW' => ['name' => 'Zambian Kwacha',            'symbol' => 'ZK'],
        ];
    }

    /** Returns ['USD' => 'USD — US Dollar ($)', ...] for Filament Select options */
    public static function selectOptions(): array
    {
        return collect(self::all())
            ->map(fn ($c, $code) => "{$code} — {$c['name']} ({$c['symbol']})")
            ->toArray();
    }

    /** Returns the symbol for a given ISO code, or null if unknown */
    public static function symbol(string $code): ?string
    {
        return self::all()[strtoupper($code)]['symbol'] ?? null;
    }
}
